### ISSUE TITLE
Backend deployment

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#57]

**Comment by patrickly** [comment]
http://wastenotcsulb-env.aewuadnmmg.us-east-1.elasticbeanstalk.com/api/items

http://wastenotcsulb-env.aewuadnmmg.us-east-1.elasticbeanstalk.com/api/categories

**Comment by patrickly** [comment]
![Screen Shot 2018-09-18 at 11.54.19 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fb6b7191a379ee0c2e55415e47bc30254d58eeb9cb74fce36f34985619e8806b0925c66b17fdb8d619bc05ba20df4fd4b4bd831ec8fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e64f5ca21b3160e170336e0a.png)

**Comment by patrickly** [comment]
[Uploading Screen Shot 2018-09-18 at 11.54.47 AM.png...]

**Comment by patrickly** [comment]
![Screen Shot 2018-09-18 at 11.54.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fb6b7191a379ee0c2e55415b49bc30254d58eeb9cb74fce36f34985619e8806b0925c66b17fdb8d619bc05ba20df4fd4b4bd831ec8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e64f5ca3173f6ae772316e0a.png)

**Comment by patrickly** [comment]
9.25.18 
Time: 1 hour. Can now delete and edit an item via the front-end. The delete and edit routes were missing, so I had to add them.
