### ISSUE TITLE
Redesign News page

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#68]
- Redesign the page to match CSULB Waste Not website/brochure's color/layout  scheme/fonts
- Create a list of news

**Comment by violangreg** [comment]
9.30.18
- Created the template for news.component.ts -- just need to link with the database
- Added the list on the html

Time: 1.5 hour

**Comment by patrickly** [comment]
10.30.18
Suggested the idea of linking the "news" button to link to " https://www.csulb.edu/sustainability/news"
Time: 10 minutes
