### ISSUE TITLE
Frontend deployment

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#71]
Able to visit the web app's domain and each link is working properly

**Comment by patrickly** [comment]
9.23.18 
Time: 1 hour watching a tutorial on Frontend Deployment.
Time: 45 min deploying older version of Waste Web App on S3.

**Comment by patrickly** [comment]
![Screen Shot 2018-09-23 at 9.59.36 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f06b7191a371f117224f5c595ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19141c95df54ce64b50a6133760e0702431.png)


---

http://wastenotcsulb.s3-website-us-east-1.amazonaws.com/

**Comment by patrickly** [comment]
9.24.18 
Time: 15 min deploying 2nd version of Waste Not web app
Time: 30 min deploying 3rd version of Waste Not web app
Time: 30 min debugging the Waste Not web app file from Pull Request #30 for front-end deployment
Time: 25 min debugging and deploying 4th version of Waste Not web app based on PR #30
Time: 15 min deploying 5th version of Waste Not web app based on PR #32. Merged PR #33 with the master branch.
Time: 1 hour 30 min deployed 6th version of Waste Not web app based on PR #34. Merged PR#34 with the master branch.
Time: 1 hour. Debugging why Editing and Deleting an Item doesn't work on live version, but you can edit or delete an item using locally. (9.25.18 UPDATE 9:48 AM) It was a backend-issue that the edit and delete functions didn't work. It's fixed now, so admins can now edit or delete an item.

**Comment by patrickly** [comment]
![Screen Shot 2018-09-24 at 6.59.11 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a37ef117224f5e5e5edd3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ce64452a2133265e2722431.png)
--
2nd version

**Comment by patrickly** [comment]
![Screen Shot 2018-09-24 at 8.15.49 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a370f1132e4f5b565edd3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ce94d57a5153465e0742431.png)
--
3rd version

**Comment by patrickly** [comment]
![Screen Shot 2018-09-24 at 8.54.42 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a370f1172f4f5b5d5edd3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ce94d51a2153f62ee752431.png)
--
Pull Request #30
Errors from running ng build --prod
https://github.com/WasteNotCSULB/WebApp/commit/b85d1c60a38b09e274cb11cc2e8e08c30ab40cc3

**Comment by patrickly** [comment]
![Screen Shot 2018-09-24 at 11.02.45 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a379ee0c2b53415b4bbc30254d58eeb9cb74fce36f34985619e8806b0925c66b17fdb8d619bc05ba20df4fd4b4bd831ec8fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e64554a6113364e274316e0a.png)
![Screen Shot 2018-09-24 at 11.02.38 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a379ee0c2b53415c46bc30254d58eeb9cb74fce36f34985619e8806b0925c66b17fdb8d619bc05ba20df4fd4b4bd831ec8fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e64554a6113364e376336e0a.png)

--
4th version

**Comment by patrickly** [comment]
--
6th version
![Screen Shot 2018-09-24 at 3.40.36 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a37bf1162b4f5c595ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ce94f5dac153f6be7712431.png)
