### ISSUE TITLE
Fix search function

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#73]

**Comment by patrickly** [comment]
9.24.18 
Time: 30 mins,  acquired a new 14-day trial of Algolia. So the search function now works.

**Comment by patrickly** [comment]
![Screen Shot 2018-09-24 at 6.01.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f76b7191a37ef1122a4f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19141c95df54ce94e52a713346ae37e2431.png)

**Comment by patrickly** [comment]
https://www.algolia.com/doc/faq/accounts-billing/do-i-need-to-display-the-algolia-logo-when-i-am-on-the-community-plan/
