### ISSUE TITLE
Improve front-end

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#74]
- Using the feedback from test front-end, change/improve the front-end

**Comment by patrickly** [comment]
10.11.18 Time: 1 hour Pair Programming (Patrick and Greg)
10.15.18 Time: 1 hour Merged front-end branch with master branch: https://github.com/WasteNotCSULB/WebApp/commit/5dfb17faa2d3612d2094b155b8035c90f946a78d

**Comment by violangreg** [comment]
10.11.18
- Redesigned home-page in regards to the feedback received.
- Took out all the unnecessary quick-access besides CRL (Compost, recycle, and landfill)
- Changed the navbar to the top
- Added a background image to make it less plain

Time: 1.5 hours

10.14.18
- Navbar re-collapses when visiting another page
- Improved page layout spacing
- Tested out different kinds of color schemes
- Cleaned up code

Time: 5 hours

**Comment by patrickly** [comment]
10.16.18 Time: 1 hour pair programming (Greg and Patrick). Clicking on a specific bin will display the bin type in the title.

**Comment by violangreg** [comment]
10.22.18
- Added case statements for bin descriptions
- Increased item count per each page on bins/browse
- Added collapsible bins nav-link dropdown

Time: 4 hours
