### ISSUE TITLE
Redesign Quiz page

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#76]
- Redesign the page to match CSULB Waste Not website/brochure's color/layout  scheme/fonts

**Comment by bto96** [comment]
9/30/18
- Worked on quiz page overhaul
Time: 5 hours

**Comment by patrickly** [comment]
10.2.18
- I debugged Brian's change to the Quiz.html and css. 
Time: 30 minutes

**Comment by bto96** [comment]
10/7/2018
- Updated quiz to new redesign
- Changed TS queries to match database changes
Time: 30 mins

**Comment by bto96** [comment]
10/16/18
- Quiz updates per testing advice
- Also improvements to homepage
Time: 30 mins

**Comment by violangreg** [comment]
10.22.18
- Added better spacing on images and answer choices
- Fixed desktop button issues
- Cleaned up code

Time: 2 hours
