### ISSUE TITLE
Contact Sustainability Office for front-end assets

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#79]
- Send a screen shot of our web app so the sustainability's graphic design intern can create the rest of the icons to match the compost, recyclable, and landfill ones
- Categories icon is going to changed to Types icon where it will have: glass, plastic, metal, paper, food, etc.
- DoD: Received assets

**Comment by bto96** [comment]
9/25/2018: 15 minutes
- Sent Holli and Lilian an email about our meeting and asking for front-end assets
