### ISSUE TITLE
Redesign nav-bar

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#80]
DoD
- nav-bar fixed at the bottom
- change the layout to icons instead of words
-> icons should be home, search, quiz, more
- remove the admin login

9.25.18 
Update:
- Change quiz icon to news icon

**Comment by violangreg** [comment]
- Changed navbar fixed to bottom
- nav-bar redesigned with proper icons and spacing

Time: 2 hours

**Comment by bto96** [comment]
- Top nav: images now properly centered vertically

Time: 15 minutes

**Comment by violangreg** [comment]
9.30.18
- Changed news icon to quiz icon

Time: 30 minutes
